# Generated by Django 2.1.1 on 2018-10-19 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verman', '0002_appdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appdate',
            name='user_add',
        ),
    ]
